image: node:14

definitions:
  services:
    postgres:
      image: postgres:11
      environment:
        POSTGRES_USER: user
        POSTGRES_PASSWORD: rootroot
        POSTGRES_DB: sgpj_db
  caches:
    node-api: packages/api/node_modules
  steps:
    - step: &lint
        name: Lint
        caches:
          - node
        script:
          - yarn install
          - yarn lint
    - step: &test
        name: Test
        caches:
          - node
          - node-api
        script:
          - apt-get update
          - apt-get install -y postgresql
          - export PG_CONNECTION_STRING=postgresql://user:rootroot@localhost/sgpj_db
          - yarn
          - yarn migrate
          - yarn test
        services:
          - postgres

pipelines:
  default:
    - step: *lint
  branches:
    master:
      - step: *test
    dev:
      - step: *test
