version: '2'

services:
  pg:
    image: postgres:13
    environment:
    - POSTGRES_USER=user
    - POSTGRES_DB=sgpj_db
    volumes:
    - pg-data:/var/lib/postgresql/data

  pgcli:
    image: pygmy/pgcli
    command: postgresql://user@pg/sgpj_db
    stdin_open: true
    tty: true
    volumes:
    - .:/app
    - pgcli-home:/root
    links:
    - pg

  api:
    build:
      context: ./docker
      args:
      - HTTP_PROXY
      - HTTPS_PROXY
      - NO_PROXY
    command: yarn start:dev
    working_dir: /app/packages/api
    tty: true
    environment:
    - HTTP_PROXY
    - HTTPS_PROXY
    - NO_PROXY
    - LOCAL_USER_ID
    ports:
    - 4000:4000
    - 9229:9229
    volumes:
    - .:/app:delegated
    - home:/home/node
    links:
    - pg
  
  app:
    build:
      context: ./docker
      args:
      - HTTP_PROXY
      - HTTPS_PROXY
      - NO_PROXY
    command: yarn dev
    working_dir: /app/packages/app
    environment:
    - HTTP_PROXY
    - HTTPS_PROXY
    - NO_PROXY
    - LOCAL_USER_ID
    ports:
    - 4001:4001
    volumes:
    - .:/app:delegated
    - /home/node
    links:
    - api

volumes:
  pg-data:
  pgcli-home:
  home: